docs/api.md
Created markdown documentation for the API.
=> API Documentation

.gitignore, package-lock.json, package.json, server.js
Added Express.js package to the project, along with a basic test function (localhost).
=> Express setup

server.js, testRequests/playlist.http, testRequests/playlists.http
Set up playlists endpoints for the API that return example JSON data:
- /api/playlists/
- /api/playlists/:playlistID - will return the same example JSON with any provided ID
=> Playlists endpoints

package-lock.json, package.json, server.js
Added pg to the project.
Added dotenv to the project.
Set up .env file.
Added some basic code for connecting to the Supabase database, but, unfortunately it has a timed out error. As a fix, have set up another database with Xata - this connection works.
=> Added npm pg to project

server.js, src/routes.js, src/routes/playlists.js, src/routes/users.js, testRequests/users.http
Adds routing using the express Router():
- /api/playlists/
- /api/users/
=> API Routing

server.js, src/routes.js, src/routes/playlists.js, src/routes/users.js
Changed from using "require" to importing the routes files - Render doesn't like "require".
- Changed server.js
- Changed routes.js
- Changed playlists.js
- Changed users.js
=> Fixed Render issue with require usage

package-lock.json, package.json, server.js
CORS package is now added and configured to our front end hosted on Netlify
=> Added cors package to the API

.env.example
Added an example environment file to the repo for documentation
=> Added example environment file

src/routes/playlists.js, src/routes/users.js
Render once again decided it suddenly doesn't like require - this time for json files, so replaced require with imports.
=> Replaced require with import

src/routes.js, src/routes/me.js, src/routes/my-playlists.js, src/routes/playlists.js, src/routes/songs.js, src/routes/users.js
Added endpoint stubs for the API which return dummy json files.
=> API endpoint stubs

src/routes/me.js, src/routes/my-playlists.js, src/routes/playlists.js, src/routes/users.js
Changed assert statements to with statements to appease Render
=> Fixed Render issue with assert

server.js, src/routes/auth.js, src/services/auth.js
A few small tweaks to enable auth...
- I'm adding the CORS restrictions back in, because we'll need them for auth
- We need to be able to post JSON data so I've added `express.json()`
- I've removed the `bio` field as the database doesn't have it, and have renamed `name` to `username` to match the database field
=> Allow auth routes to post content

src/routes/my-playlists.js, src/routes/playlists.js
Fixed JSON responses from /api/playlists/:playlistID and /api/my-playlists/:playlistID not returning the songs in the specified playlist.
=> Playlists songs fix

src/routes/auth.js, src/routes/me.js, src/routes/my-playlists.js, src/routes/playlists.js, src/routes/users.js
Added logging using console.error() to API endpoints.
=> Database error logging

package-lock.json, package.json
Installed the nodemon npm package
=> Added nodemon package

src/routes/playlists.js
=> Fixed playlist const

src/routes/me.js, src/routes/users.js
The database query was returning sensitive user data. Updated the code so it returns only public data.
=> Remove sensitive data

src/routes/my-playlists.js, src/routes/playlists.js
Changes my-playlists endpoints to use the same database access logic as playlists.
Also adds a check in both endpoints to return 404 if the specified playlist isn't in the database.
=> Endpoints review

docs/api.md, src/routes/my-playlists.js
Fixes auth issues with my-playlists endpoints.
=> Endpoint testing

src/routes/me.js
Fixes the me endpoints not being able to get the user id by getting it from req.user.id instead of req.params
=> Fixed me endpoints not being able to get user id
